---
title: "viz_eda"
output: github_document
date: "2025-09-30"
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(patchwork)
library(p8105.datasets)
```

```{r}
data("weather_df")
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.5) +
  #adding labels
  labs(
    x = "Minimum daily temp",
    y = "Maximum daily temp",
    title = "Temperature scatterplot",
    caption = "Data from NOAA",
    color = "Location"
  )
```



## Scales
```{r}
ggp_temp = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.5) +
  #adding labels
  labs(
    x = "Minimum daily temp",
    y = "Maximum daily temp",
    title = "Temperature scatterplot",
    caption = "Data from NOAA",
    color = "Location") +
  #trying to change something on x-axis and x-axis is continuous
  scale_x_continuous(
    breaks = c(-20,0,25),
    labels = c("-20C","0","25")
  ) +
  #changing color palette
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE
  )

```


Update Base Plot
```{r}
ggp_temp +
  theme_dark() +
  theme(legend.position = "bottom") 

print(ggp_temp)
```


## Adding data in geoms

```{r}
central_park_df =
  weather_df |> 
  filter(name == "CentralPark_NY")


molokai_df =
  weather_df |> 
  filter(name == "Molokai_HI")

#use on dataset for one part of my plot and bring in another dataset
ggplot(data = molokai_df, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park_df)

```


## `patchwork`
Make three plots and combine using patchwork

```{r}
ggp_tmax_tmin =
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  theme(legend.position = "none")


ggp_prec_density =
  weather_df |> 
  filter(prcp > 0) |> 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.5) +
  theme(legend.position = "none")


ggp_temp_season =
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")

#putting plots side by side
(ggp_tmax_tmin + ggp_prec_density) / ggp_temp_season

```


## Data manipulation
Lets make temperature violin plots

```{r}
  #telling what order the variables go in by releveling, assign molokai-1, central park-2 and putting them in order.
weather_df |> 
  mutate(name = fct_relevel(name,c("Molokai_HI","CentralPark_NY","Waterhole_WA"))) |> 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin(alpha = 0.5)
```

```{r}
#whats the average tmax and put it in order from smallest ot largest
weather_df |> 
  mutate(name = fct_reorder(name, tmax))  |> 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin(alpha = 0.5)
```


What about data tidiness?
```{r}
#does distribution change? issue: data is not structured in order to make comparison so need to tidy becuase bdi score is spread across columns
pulse_df =
  haven::read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) |> 
  mutate(visit = fct_inorder(visit)) #putting visit in order that it appears in the dataset


pulse_df |> 
  ggplot(aes(x = visit, y = bdi)) +
  geom_boxplot()


pulse_df

```


Make a plot for the FAS study
```{r}
pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA",".",""), skip = 3) |> 
  janitor::clean_names() |> 
  mutate(
    sex = case_match(
      sex,
      1 ~ "male",
      2 ~ "female"
    )
  )

litter_df =
  read_csv("data/FAS_litters.csv", na = c("NA",".","")) |> 
  janitor::clean_names() |> 
  separate(group, into = c("dose","tx_day"), sep = 3)

fas_df =
  left_join(pups_df, litter_df, by = "litter_number")

fas_df |> 
  select(pd_ears:tx_day) |> 
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome",
    names_prefix = "pd_",
    values_to = "pn_day"
  ) |> 
  drop_na() |> 
  ggplot(aes(x = dose, y = pn_day)) +
  geom_violin() +
  facet_grid(tx_day ~ outcome)

```















